### ISSUE TITLE
json service registry file name does not match service ID when saving new service in cas-manager

### ISSUE THREAD

**Issue by leeyc0** [apereo/cas#2590]
Just discovered when I am saving a new service, the service ID does not match that of filename.

For example when I save a new service, the service definition is

```yml
{
  @class: org.apereo.cas.services.RegexRegisteredService
  serviceId: ddd
  name: dddddd
  id: 21781220181051640
  description: aaa
  proxyPolicy:
  {
    @class: org.apereo.cas.services.RefuseRegisteredServiceProxyPolicy
  }
  evaluationOrder: 1
  usernameAttributeProvider:
  {
    @class: org.apereo.cas.services.DefaultRegisteredServiceUsernameProvider
    canonicalizationMode: NONE
    encryptUsername: false
  }
  attributeReleasePolicy:
  {
    @class: org.apereo.cas.services.ReturnAllAttributeReleasePolicy
    principalAttributesRepository:
    {
      @class: org.apereo.cas.authentication.principal.DefaultPrincipalAttributesRepository
      expiration: 2
      timeUnit: HOURS
    }
    authorizedToReleaseCredentialPassword: false
    authorizedToReleaseProxyGrantingTicket: false
    excludeDefaultAttributes: false
  }
  multifactorPolicy:
  {
    @class: org.apereo.cas.services.DefaultRegisteredServiceMultifactorPolicy
    failureMode: CLOSED
    bypassEnabled: false
  }
  accessStrategy:
  {
    @class: org.apereo.cas.services.DefaultRegisteredServiceAccessStrategy
    enabled: true
    ssoEnabled: true
    requireAllAttributes: false
    caseInsensitive: false
  }
```
However I found the filename is dddddd-21781220181051638.json instead. This would cause trouble when editing a service and creating two identical services (but with different filename dddddd-21781220181051640.json. I have to go to the server to delete the "wrong" service json directly to fix.
